Stack calculaor
IliaSotnikov2005/2ndSemesterHomeworks pull request #2
Opened 2024-02-25 17:42 UTC by IliaSotnikov2005

2024-03-02 09:37 UTC, TimaFrolov requested changes
1 / 5

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
Стоит для каждого интерфейса и класса завести отдельный файл
+ мейн вытащить из StackCalculator в top-level

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +/// <typeparam name="T"></typeparam>
Здесь или описание, что это за параметр, или убрать эту строку

И так везде

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +    }
К публичным методам нужна документация (а ещё между методами стоит оставлять пустую строку)
Если хочется просто скопировать документацию интерфейса - `inheritdoc` в помощь

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +        size++;
К полям класса стоит обращаться с использованием `this`:
```suggestion
        this.list.Add(value);
        this.size++;
```
И такое стоит сделать везде

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +    /// <param name="capacity">Maximum size of stack.</param>
Такого параметра, кажется, нет

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +    /// Getter for stack size.
SA1623: The property's documentation summary text should begin with: 'Gets' (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/mas
ter/documentation/SA1623.md)
Вообще, можно добавлять в зависимости `StyleCop.Analyzers`, он при сборке будет выводить почти все (а может и все) стилистические ошибки, о которых я пишу и даже больше. Если это самое "больше" кажется черсчур и соблюдать не хочется - часть варнингов можно выключить

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +    /// <param name="stackType">Type of stack to be used. Default is StackOnList</param>
SA1629: Documentation text should end with a period (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1629.md)

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +        }
Внимательно читаем условие и находим: "Стековый калькулятор должен знать только про интерфейс стека (то есть вообще в коде класса «Стековый калькулятор» не должно быть ни одного упоминания конкретных реализаций стека, даже если очень хочется)."
:disappointed:

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +            throw new InvalidOperationException("Stack is empty");
Все кидаемые исключения тоже надо документировать
Если интерфейс подразумевает исключения - документацию на них стоит писать в интерфейсе

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +        }
Можно сделать так:
```suggestion
        if (size == 0)
        {
            throw new InvalidOperationException("Stack is empty");
        }

        size--;
        T returningValue = array[size];
        array[size] = default;
        return returningValue;
```
И тогда содержательная часть функции не будет убегать вправо

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +            T returningValue = list[^1];
`list[^1]` выглядит страшно, и не сразу понятно, что имелось ввиду

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +    }
Можно написать короче:
```suggestion
    public int Size => this.size;
```
А ещё можно было бы завести `public int Size {get;  private set;};` вместо `private int size;`

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +            Array.Copy(array, tempArray, array.Length);
А `Array.Resize` случаем не подойдёт для такого?

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +        array[size] = value;
Присваиваем лишний раз

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +            array[size] = default;
warning CS8601: Possible null reference assignment.

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +            {
```suggestion
                stack.Push(number);
                continue;
            }
```
И весь последующий код из блока `else`

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +                            if (Math.Abs(operand1) < float.Epsilon)
Не уверен, что `float.Epsilon` - то, с чем стоит сравнивать :thinking: по документации это наименьшее представимое число, большее нуля. Т.е. эта проверка в целом эквивалентна `== 0`, чего хочется избежать. 
Неснимаемый минус балл за это не ставлю, но стоит завести собственную дельту побольше этой

2024-03-02 09:37 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +        float[] expected = { -8, 0, 0 };
А если я вставляю `216 6 3 8 4 + * / -`, то получаю `215.83333`.

2024-03-02 15:25 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +            T returningValue = list[^1];
А, я почитал, и это вполне нормально, просто я раньше, видимо, не встречал. Если что, можно оставить

2024-03-02 16:08 UTC, TimaFrolov requested changes
Осталось небольшое, 5/5
Но `size` у `StackOnArray` стоит исправить, потому что должно вылезти при тестировании (а если не вылезло - надо добавить тест на это)

2024-03-02 16:08 UTC, TimaFrolov commented on StackCalculator/.editorconfig
красивое

2024-03-02 16:08 UTC, TimaFrolov commented on StackCalculator/.editorconfig
> +dotnet_diagnostic.SA1514.severity = none
Вообще, я бы сказал, эта штука дельная. Заставляет следить за пустыми строками между функциями
А в начале файла по хорошему стоит ставить `namespace`

2024-03-02 16:08 UTC, TimaFrolov commented on StackCalculator/Program.cs
> +Console.WriteLine($"\nThe result: {StackCalculator.Calculate(expression, new StackOnList<float>())}");
Вообще, было бы неплохо ловить эксепшены из `Calculate` и выводить пользователю аккуратное сообщение о том, что пошло не так

2024-03-02 16:08 UTC, TimaFrolov commented on StackCalculator/StackOnArray.cs
> +    public int Size { get; private set; }
Как-то вышло так, что ты наружу неправильный `Size` выставил

2024-03-02 16:10 UTC, TimaFrolov commented
Ещё было бы хорошо сразу в последующих домашках поправить общие замечания (в духе стайл гайд анализатора), всё равно придётся, когда я дойду до них

2024-03-02 16:50 UTC, merged

2024-03-05 14:31 UTC, zhitm commented on StackCalculator/StackOnArray.cs
> +            Array.Resize(ref this.array, this.Size * 2);
[This method](https://learn.microsoft.com/ru-ru/dotnet/api/system.array.resize?view=net-8.0) allocates a new array with the specified size, copies elements from the old array to the new one, and then replaces the old array with the new one

Каждый раз создавать новый массив не очень эффективно

2024-03-05 14:31 UTC, zhitm commented on StackCalculator/StackOnArray.cs
> +            Array.Resize(ref this.array, this.Size * 2);
не туда.